<!-- ===============================================-->
<!--    JavaScripts-->
<!-- ===============================================-->
<script src="{{asset('admin/vendors/codeanddeploy.tablecheckall/table-check-all.js')}}"></script>
<script src="{{asset('admin/vendors/list.js/list.min.js')}}"></script>
<script src="{{asset('admin/vendors/countup/countUp.umd.js')}}"></script>
<script src="{{asset('admin/vendors/dropzone/dropzone.min.js')}}"></script>
<script src="{{asset('admin/vendors/popper/popper.min.js')}}"></script>
<script src="{{asset('admin/vendors/bootstrap/bootstrap.min.js')}}"></script>
<script src="{{asset('admin/vendors/anchorjs/anchor.min.js')}}"></script>
<script src="{{asset('admin/vendors/is/is.min.js')}}"></script>
<script src="{{asset('admin/vendors/echarts/echarts.min.js')}}"></script>
<script src="{{asset('admin/vendors/fontawesome/all.min.js')}}"></script>
<script src="{{asset('admin/vendors/lodash/lodash.min.js')}}"></script>
<script src="{{asset('admin/assets/js/theme.js')}}"></script>
<script src="{{asset('admin/assets/data/world.js')}}"></script>
<script src="{{asset('admin/vendors/chart/chart.min.js')}}"></script>
<script src="{{asset('admin/vendors/dayjs/dayjs.min.js')}}"></script>
<script src="{{asset('admin/vendors/overlayscrollbars/OverlayScrollbars.min.js')}}"></script>
<script src="{{asset('admin/assets/js/flatpickr.js')}}"></script>

